### PR TITLE
Enabled the firewall again.

### PR DESCRIPTION
**Pull request by digimer**
This is fully expected to fail initially.

### CODE REVIEW

**Comment by ylei-tsubame** [comment]
Please test the VNC connection from the web UI.

The VNC-to-websocket translation is done by `websockify` on a server's `VNC port + 10000`. For example, a server with VNC port `5900` should have the `websockify` port (listening to incoming connections) at `15900`.

The port selection for the `websockify` instance will also jump to the next available port when the suggested one is in-use. For example, if ports `15900` and `15901` are in-use, then port `15902` will be selected as the `websockify` port. We shouldn't need to worry about this because there shouldn't be any known apps using ports in this area.

**Comment by digimer** [comment]
What command specifically is used to check if a port is in use and needs to be incremented? I can do the same check when opening the corresponding port.

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
This PR now passes automated testing. Manual testing now required before merge.

**Pull request merged**
