### PR TITLE
Web UI: dependabot issues 53 (axios), 57 (next)

### PR DESCRIPTION
**Pull request by ylei-tsubame**
This PR doesn't change code outside of `striker-ui*` folders, so it shouldn't affect the outcome of CI tests; should be safe to merge without needing a pass? Next PRs need to wait until this one merges.

Closes #529
Closes #662

### CODE REVIEW

**Review by digimer — APPROVED** [review]

**Comment by ylei-tsubame** [comment]
retest this please

**Comment by ylei-tsubame** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
You should be able to rebase against main and try building this PR again.

**Pull request merged**
