### PR TITLE
Enable SELinux

### LINKED ISSUE #364: Enable SELinux
Before GA

### PR DESCRIPTION
**Pull request by ylei-tsubame**
Closes #364

### CODE REVIEW

**Comment by digimer** [comment]
retest this please

**Comment by ylei-tsubame** [comment]
retest this please

**Comment by ylei-tsubame** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Review by digimer — APPROVED** [review]

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Review by digimer — APPROVED** [review]

**Pull request merged**
