### PR TITLE
Web UI bundle 20221125

### PR DESCRIPTION
**Pull request by ylei-tsubame**
This is a bundle of several modules in the web UI (including the supporting API).

Modules:
* Prepare host form
* Provision server form
* Server list (new homepage)
* Striker initialization form
* Striker configuration form

~~This PR is **not ready** at the moment; it will be updated later.~~
Update 20221128: This PR is now ready for merging.

### CODE REVIEW

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Review by digimer — APPROVED** [review]

**Pull request merged**
