### PR TITLE
Migrate from `mailx` to `s-nail` on RHEL/Almalinux >= 9

### LINKED ISSUE #679: mailx to s-nail transition
mailx has been deprecated in f39 in favor of s-nail.

The current external repo dependencies still carry mailx from f37.

For rhel-8/centos-8-stream we can just leave it as-is as both are being slowly replaced by 9.

For rhel-9/almalinux-9 we need to transition to a more recent version of all the external dependencies. That includes:

1. add s-nail to the external repo (f40 based)
2. change anvil spec file to Conflics mailx and Requires s-nail for >= 9
3. change anvil code to use s-nail

It is unknown if s-nail is command line compatible with mailx, but it does provide the same functionalities.

Not targeting any specific anvil release for now as updating the external repo has to be coordinate and tested.

### PR DESCRIPTION
**Pull request by ylei-tsubame**
Closes #679

### CODE REVIEW

**Comment by ylei-tsubame** [comment]
Although the test failed, I've confirmed that `s-nail` is correctly installed on RHEL 9 and Almalinux 9. Also confirmed `mailx` is functional as expected on RHEL 8.

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Pull request merged**
