### PR TITLE
Web UI: pre-3.0-beta

### PR DESCRIPTION
**Pull request by ylei-tsubame**
This PR is expected to be the last PR pre-3.0-beta (and must be the last huge PR...).

~~**Don't merge!** Leaving it in draft until the web UI pieces are OK for release.~~

**Update 20230703**: all web UI and API pieces are functional at this point. Suggest re-testing before merging as current test(s) may be based on outdated `main` branch.

### CODE REVIEW

**Comment by fabbione** [comment]
@ylei-tsubame can you please rebase your PR on top of latest main branch? Otherwise you are testing old code from core.

**Comment by digimer** [comment]
This build failure appears to be related to a pacemaker issue, not a code issue. Investigating.

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Review by digimer — APPROVED** [review]

**Pull request merged**
