### PR TITLE
This branch resolves issue #462; Auto growing PVs. Specifically, it l…

### PR DESCRIPTION
**Pull request by digimer**
…ooks at the LVM PVs on the host and checks to see if there is unused free space after the backing partition. If there is, it auto-grows the partition and then resizes the PV. This featu

re is designed to make life easier for users who deleted the auto-created '/home' partition during the anaconda disk partitioning tool.
* Created Storage->auto_grow_pv() that does the above.
* Added the missing hidden method name _create_rsync_wrapper in the Storage module POD.
* Added a call to Storage->auto_grow_pv() in anvil-configure-host and anvil-version-changes for nodes and DR.

### CODE REVIEW

**Comment by fabbione** [comment]
I have a few issues with this approach:

1. re-reading the partition tables on some devices requires a node reboot (hence needs to be planned).
2. what if the user is creating space to have another storage group instead?
3. one node fails, we replace the node with another one that has bigger disks than the peer node. the pv size will go asymmetric between the nodes.
4. what if the process fails in between operations? you are left with a potentially damaged partition table.

IMHO, rather than autogrow, this should be available as (from UI):

we detected that there is free space on the device, would you like to extend any of the current storage groups or create a new one or leave it there because you don´t need it?

**Comment by digimer** [comment]
I removed the calls from anvil-version-change, as this should only ever need to be used once. I'm leaving it in anvil-configure-host because that only runs when the machine is being first configured, and even then it sets maintenance mode so there's no way it should be in the cluster (it's run to initially configure the network, so it's almost certainly not in any cluster at that point). 

1. In my experience, anything modern will see the changes to disk immediately, perhaps needing a call to part-probe, but I've not needed that in my experience with any relatively modern OS. In any case, the machine is likely about to reboot from the network remap.
2. Storage groups are built on VGs, this function simply adds the unused storage to the existing PV. So the VG will now have more space. Generally storage groups are unique to raw blocks of storage (ie: nvme array vs a large bulk storage platter array). If someone somehow really wants to have a different PV on the same backing storage, we can tell them to create it during OS install or prior to installing our RPMs. In most cases, because anaconda makes the PV only big enough for the requested LVs at install time, the need to grow manually is almost always there.
3. The system is designed to account for unequal VG sizes. Storage groups set by the smaller of the available PVs. 
4. Fail in what regard?  There are two calls; First is to parted to resize the part, and the RC is checked. If that fails. nothing changes. If it succeeds, it calls pvresize. That's checked also, and if it fails (which I've never seen happen), nothing changes. Am I missing a failure mode?

I will create an issue for 3.1 to add a button to initializing hosts that says "Do you want to use any free space in storage groups?" and default select it, and remove the auto-grow then. In the meantime, this makes our software work with minimal user input when they follow our instructions on the wiki.

**Comment by fabbione** [comment]
> I removed the calls from anvil-version-change, as this should only ever need to be used once. I'm leaving it in anvil-configure-host because that only runs when the machine is being first configured, and even then it sets maintenance mode so there's no way it should be in the cluster (it's run to initially configure the network, so it's almost certainly not in any cluster at that point).

It´s nothing to do with clustering here. Cluster is not involved. It´s the design that is not ok as a concept.

> 
>     1. In my experience, anything modern will see the changes to disk immediately, perhaps needing a call to part-probe, but I've not needed that in my experience with any relatively modern OS. In any case, the machine is likely about to reboot from the network remap.

It fails miserably to reprobe partitions if it´s the disk with the root partition. modern or not. I see this even in RHEL9 or up. It´s a kernel lock on the disk that you can´t workaround.
> 
>     2. Storage groups are built on VGs, this function simply adds the unused storage to the existing PV. So the VG will now have more space. Generally storage groups are unique to raw blocks of storage (ie: nvme array vs a large bulk storage platter array). If someone somehow really wants to have a different PV on the same backing storage, we can tell them to create it during OS install or prior to installing our RPMs. In most cases, because anaconda makes the PV only big enough for the requested LVs at install time, the need to grow manually is almost always there.

I understand what it does, but it´s an extra level of complication for the user to partition the system differently to start with, if this code is executed.

> 
>     3. The system is designed to account for unequal VG sizes. Storage groups set by the smaller of the available PVs.

ack

> 
>     4. Fail in what regard?  There are two calls; First is to parted to resize the part, and the RC is checked. If that fails. nothing changes. If it succeeds, it calls pvresize. That's checked also, and if it fails (which I've never seen happen), nothing changes. Am I missing a failure mode?

if the partition resize fail, you can end up with a broken partition table and a node unable to boot or use the storage at the next boot. RC doesn´t tell you what failed in the resizing operation.

At least the whole logic has to be improved by taking a backup of the partition blocks before attempting the resize, do the resize, on failure attempts to restore from backup, if fails... well you are doomed.

> 
> 
> I will create an issue for 3.1 to add a button to initializing hosts that says "Do you want to use any free space in storage groups?" and default select it, and remove the auto-grow then. In the meantime, this makes our software work with minimal user input when they follow our instructions on the wiki.

**Comment by digimer** [comment]
Notes me me;

Backup partition table;
`sfdisk --dump /dev/sda > partition_table_backup_sda`

Restore;
`sfdisk --dump /dev/sda > partition_table_backup_sda`

Backup gpt partition table;
`

**Comment by digimer** [comment]
I am going to make this a switch used with anvil-manage-host, so the user has to explicitly run it, with proper warnings. I'll also be adding in the backup/restore of the partition table, as per comment above. Later, we'll make a user-enableable switch when initializing the subnode or DR host, again with appropriate warnings.

**Comment by digimer** [comment]
Warning given to the user;

```
[ Warning ] - Auto-growing the LVM physical volumes could, in some case, leave the system unbootable.
The steps that will taken are;
- LVM Pyhiscal volumes will be found.
- For each found, 'parted' is used to see if there is > 1GiB of free space available.
- If so, and if no other partitions are after it, it will be grown to use the free space.
- The PV itself will then be resized to use the new space

This is generally used just after initializing a new subnode or DR host. If this host has real data
on it, please proceed with caution. 

The partition table will be backed up, and if the partition resize fails, the partition table will be
reloaded automatically. If this host has real data, ensure a complete backup is available before 
proceeding.
```

**Comment by digimer** [comment]
retest this please

**Review by fabbione — APPROVED** [review]

**Pull request merged**
