### PR TITLE
Web UI: adjust messages during file uploads

### LINKED ISSUE #488: When uploading files, the upload shows as complete but the file(s) don't get added to the 'files' table
I was able to upload one file OK, but not any others. I tried uploading the 'virtio' file from the screenshot below, and when the progress bar as at 100%, I closed the interstitial menu, expecting it to show up in a minute. It didn't, so I thought it was a problem with closing that window too soon. So I tried uploading it again, along with a second file, and neither showed up.

EDIT: See below;

image

image

As I was writing this, one of the two files showed up in the DB, the larger file, but the virtio (which I had previously tried to upload) was still not there, but it was in incoming still.

image

image

After enough time, it finally added. I think what's needed is to ensure that once the file is uploaded to striker, some way to show the user that the file is still being processed is important, so that they don't think (like I did) that the upload failed.

### PR DESCRIPTION
**Pull request by ylei-tsubame**
Note: this PR doesn't include a rebuild; it will be included in the next PR.

Closes #488

### CODE REVIEW

**Review by digimer — APPROVED** [review]

**Comment by ylei-tsubame** [comment]
retest this please

**Comment by ylei-tsubame** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Pull request merged**
