### PR TITLE
Anvil tools dev

### PR DESCRIPTION
**Pull request by digimer**
DO NOT MERGE

This PR is almost certainly going to fail, and probably many times. This PR adds Network Manager support, deprecating ifcfg files. The primary reason for the PR being created early is to get extensive testing.

### CODE REVIEW

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by digimer** [comment]
This is NOT ready for merging! Marked it as ready for review for more thorough testing

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Pull request closed without merging**
