### PR TITLE
Update testing

### PR DESCRIPTION
**Pull request by digimer**

### CODE REVIEW

**Comment by digimer** [comment]
This PR will close issue #649 and issue #385

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
Merging, will continue to watch for upgrade test issues with builds of future PRs.

**Pull request merged**
