### PR TITLE
Anvil tools dev

### PR DESCRIPTION
**Pull request by digimer**
Adding performance logging.

### CODE REVIEW

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
Retest this please

**Comment by digimer** [comment]
retest this please

**Pull request merged**
