### PR TITLE
Added a work-around for an LVM JSON formatting issue

### PR DESCRIPTION
**Pull request by digimer**
* Related to https://issues.redhat.com/browse/RHEL-29680
* Updated Storage->manage_lvm_conf() to be stricter about when to add the filter to lvm.conf

### CODE REVIEW

**Comment by fabbione** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by digimer** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Pull request merged**
